CREATE TABLE locate (ID INT NOT NULL PRIMARY KEY auto_increment, 
	UserID BIGINT, 
	TITLE VARCHAR(255), 
	ICON VARCHAR(255), 
	FLAG BIGINT, 
	REMARK VARCHAR(255));
ALTER TABLE locate ADD ogc_geom GEOMETRY; 